#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Zig version
#
# Usage: zigenv local <version>
#        zigenv local --unset
#
# Sets the local application-specific Zig version by writing the
# version name to a file named `.zig-version'.
#
# When you run a Zig command, zigenv will look for a `.zig-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, zigenv will use the global Zig version
# specified with `zigenv global'. A version specified with the
# `ZIGENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a Zig version known to zigenv.
# The special version string `system' will use your default system Zig.
# Run `zigenv versions' for a list of available Zig versions.

set -e
[ -n "$ZIGENV_DEBUG" ] && set -x

# Provide zigenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec zigenv-versions --bare
fi

ZIGENV_VERSION="$1"

if [ "$ZIGENV_VERSION" = "--unset" ]; then
  rm -f .zig-version
elif [ -n "$ZIGENV_VERSION" ]; then
  zigenv-version-file-write .zig-version "$ZIGENV_VERSION"
else
  if version_file="$(zigenv-version-file "$PWD")"; then
    zigenv-version-file-read "$version_file"
  else
    echo "zigenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
