#!/usr/bin/env bash
# Summary: Show the current Zig version and its origin
#
# Shows the currently selected Zig version and how it was
# selected. To obtain only the version string, use `zigenv
# version-name'.

set -e
[ -n "$ZIGENV_DEBUG" ] && set -x

VERSION_NAME="$(zigenv-version-name)"
VERSION_PATH="$(zigenv-prefix "$VERSION_NAME" 2>/dev/null || true)"

while [ -L "$VERSION_PATH" ]; do
  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || break

  VERSION_PATH=$($READLINK "$VERSION_PATH")
  ALIAS=$(basename "$VERSION_PATH")
done

echo "$VERSION_NAME ${ALIAS+=> $ALIAS }(set by $(zigenv-version-origin))"
