#!/usr/bin/env bash
# Summary: List hook scripts for a given zigenv command
# Usage: zigenv hooks <command>

set -e
[ -n "$ZIGENV_DEBUG" ] && set -x

# Provide zigenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

ZIGENV_COMMAND="$1"
if [ -z "$ZIGENV_COMMAND" ]; then
  zigenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/zigenv-realpath.dylib realpath 2>/dev/null; then
  READLINK=$(type -p greadlink readlink 2>/dev/null | head -1)
  if [ -z "$READLINK" ]; then
    echo "zigenv: cannot find readlink - are you missing GNU coreutils?" >&2
    exit 1
  fi

  resolve_link() {
    $READLINK "$1"
  }

  realpath() {
    local cwd="$PWD"
    local path="$1"
    local name

    while [ -n "$path" ]; do
      name="${path##*/}"
      [ "$name" = "$path" ] || cd "${path%/*}"
      path="$(resolve_link "$name" || true)"
    done

    echo "${PWD}/$name"
    cd "$cwd"
  }
fi

IFS=: hook_paths=($ZIGENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$ZIGENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
