#!/usr/bin/env bash
# Summary: List existing zigenv shims
# Usage: zigenv shims [--short]

set -e
[ -n "$ZIGENV_DEBUG" ] && set -x

# Provide zigenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${ZIGENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
