#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Zig version
#
# Usage: zigenv shell <version>
#        zigenv shell -
#        zigenv shell --unset
#
# Sets a shell-specific Zig version by setting the `ZIGENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Zig version known to zigenv.
# The special version string `system' will use your default system Zig.
# Run `zigenv versions' for a list of available Zig versions.
#
# When `-` is passed instead of the version string, the previously set
# version will be restored. With `--unset`, the `ZIGENV_VERSION`
# environment variable gets unset, restoring the environment to the
# state before the first `zigenv shell` call.

set -e
[ -n "$ZIGENV_DEBUG" ] && set -x

# Provide zigenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec zigenv-versions --bare
fi

version="$1"
shell="$(basename "${ZIGENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$ZIGENV_VERSION" ]; then
    echo "zigenv: no shell-specific version configured" >&2
    exit 1
  else
    echo 'echo "$ZIGENV_VERSION"'
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo 'set -gu ZIGENV_VERSION_OLD "$ZIGENV_VERSION"'
    echo "set -e ZIGENV_VERSION"
    ;;
  * )
    echo 'ZIGENV_VERSION_OLD="$ZIGENV_VERSION"'
    echo "unset ZIGENV_VERSION"
    ;;
  esac
  exit
fi

if [ "$version" = "-" ]; then
  case "$shell" in
  fish )
    cat <<EOS
if set -q ZIGENV_VERSION_OLD
  if [ -n "\$ZIGENV_VERSION_OLD" ]
    set ZIGENV_VERSION_OLD_ "\$ZIGENV_VERSION"
    set -gx ZIGENV_VERSION "\$ZIGENV_VERSION_OLD"
    set -gu ZIGENV_VERSION_OLD "\$ZIGENV_VERSION_OLD_"
    set -e ZIGENV_VERSION_OLD_
  else
    set -gu ZIGENV_VERSION_OLD "\$ZIGENV_VERSION"
    set -e ZIGENV_VERSION
  end
else
  echo "zigenv: ZIGENV_VERSION_OLD is not set" >&2
  false
end
EOS
    ;;
  * )
    cat <<EOS
if [ -n "\${ZIGENV_VERSION_OLD+x}" ]; then
  if [ -n "\$ZIGENV_VERSION_OLD" ]; then
    ZIGENV_VERSION_OLD_="\$ZIGENV_VERSION"
    export ZIGENV_VERSION="\$ZIGENV_VERSION_OLD"
    ZIGENV_VERSION_OLD="\$ZIGENV_VERSION_OLD_"
    unset ZIGENV_VERSION_OLD_
  else
    ZIGENV_VERSION_OLD="\$ZIGENV_VERSION"
    unset ZIGENV_VERSION
  fi
else
  echo "zigenv: ZIGENV_VERSION_OLD is not set" >&2
  false
fi
EOS
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if zigenv-prefix "$version" >/dev/null; then
  if [ "$version" != "$ZIGENV_VERSION" ]; then
    case "$shell" in
    fish )
      echo 'set -gu ZIGENV_VERSION_OLD "$ZIGENV_VERSION"'
      echo "set -gx ZIGENV_VERSION \"$version\""
      ;;
    * )
      echo 'ZIGENV_VERSION_OLD="$ZIGENV_VERSION"'
      echo "export ZIGENV_VERSION=\"$version\""
      ;;
    esac
  fi
else
  echo "false"
  exit 1
fi
